#!/bin/bash

#------------------------------------------------------------------#
# Author: OBED PAUL
# Created Date: 27/03/2025
# Modified Date: 27/03/2025

# Description:
# using range list {1..12} returns -> 1 2 3 4 5 6 7 8 9 10 11 12

# Usage:
# ./8_rangelist
#------------------------------------------------------------------#

# Level 1: print 01 -> 12------------------------------@

echo {01..12}
echo {01..10..2}
echo {01..10..3}
echo {02..12..4}


# Level 2: make directory for month01 -> month12-------@

mkdir month{01..12}

rm -rf month* # removing for better understanding of next level


# Level 3: --------------------------------------------@
# make directories for month01 -> month12
# within each directory create day01.txt -> day31.txt
mkdir month{01..12}

touch month{01..12}/day{01..31}.txt
# once done with the excersie please delete the generated spam files

exit 0
