name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd python-app
          python3 -m pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd python-app
          python3 -m unittest test_app.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to staging server
        run: |
          scp -r python-app ec2-user@3.83.174.167:/home/ec2-user/app
          ssh ec2-user@3.83.174.167 "cd /home/ec2-user/app && nohup python3 visitcount.py > /dev/null 2>&1 &"
