name: CI/CD Pipeline

#this section is commented to avoid running of duplicate job, 
#the script is aldready tested and is woring please do refer the actions section to verify to output

#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd python-app
          python3 -m pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd python-app
          python3 -m unittest test_app.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to staging server
        run: |
          scp -r python-app ec2-user@3.83.174.167:/home/ec2-user/app
          # SSH into the server and deploy the new app
          ssh ec2-user@3.83.174.167 << 'EOF'
          cd /home/ec2-user/app

          # Stop the old app (if running)
          pkill -f "python3 visitcount.py" || true

          # Install dependencies (if needed)
          pip install -r requirements.txt

          # Start the new app
          nohup python3 visitcount.py > /dev/null 2>&1 &
          EOF
